import { describe, expect, it } from 'vitest';

import vectors from './receipt-vectors.json';
import { exchangeDigest, receiptSigningDigest, verifyReceipt, type Receipt } from './receipt';
import type { Message } from './index';

/**
 * Pinning this transcription of the receipt layout to the node's.
 *
 * A receipt is evidence only if two implementations agree byte-for-byte on what
 * was signed, and a second transcription that drifts does not fail loudly: it
 * fails as "invalid signature", which reads as a key problem and sends a reader
 * looking somewhere else while every receipt on the network quietly stops
 * verifying.
 *
 * So these are not three hand-written examples. `receipt-vectors.json` is
 * generated by the Go implementation (go test ./internal/inference -run
 * TestWriteReceiptVectors) over inputs chosen where two implementations diverge
 * rather than where they agree: empty strings, zero numbers, multi-byte text,
 * and values above 2^53 where a JavaScript number silently stops being exact.
 */

interface Vector {
  name: string;
  receipt: Receipt;
  signing_digest: string;
  prompt: string;
  completion: string;
  exchange_digest: string;
}

const cases = vectors as unknown as Vector[];

function hex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

// A prompt-only request is one user message, which is what the node's
// EffectiveMessages produces. An empty prompt is no messages at all.
function messagesFor(prompt: string): Message[] {
  return prompt.trim() === '' ? [] : [{ role: 'user', content: prompt }];
}

describe('the receipt layout matches the node byte for byte', () => {
  it('has vectors to check against', () => {
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const v of cases) {
    it(`signs the same bytes: ${v.name}`, async () => {
      expect(hex(await receiptSigningDigest(v.receipt))).toBe(v.signing_digest);
    });

    it(`hashes the same exchange: ${v.name}`, async () => {
      expect(hex(await exchangeDigest(messagesFor(v.prompt), v.completion))).toBe(v.exchange_digest);
    });

    it(`verifies a receipt the node signed: ${v.name}`, async () => {
      const check = await verifyReceipt(v.receipt, {
        messages: messagesFor(v.prompt),
        completion: v.completion,
        buyer: v.receipt.buyer,
      });
      expect(check.problem).toBeUndefined();
      expect(check.signatureValid).toBe(true);
      expect(check.boundToExchange).toBe(true);
    });
  }
});

describe('what a receipt refuses', () => {
  const base = () => structuredClone(cases[0]) as Vector;

  it('refuses a receipt shown for a different exchange', async () => {
    const v = base();
    const check = await verifyReceipt(v.receipt, {
      messages: messagesFor('a different question entirely'),
      completion: v.completion,
    });
    expect(check.signatureValid).toBe(true);
    expect(check.boundToExchange).toBe(false);
  });

  it('refuses a receipt whose claims were edited', async () => {
    const v = base();
    // The field that makes a substitution attributable rather than deniable.
    v.receipt.model = 'a-much-cheaper-model';
    const check = await verifyReceipt(v.receipt);
    expect(check.signatureValid).toBe(false);
  });

  it('refuses a receipt whose total was edited', async () => {
    const v = base();
    v.receipt.total = String(BigInt(v.receipt.total) * 2n);
    const check = await verifyReceipt(v.receipt);
    expect(check.signatureValid).toBe(false);
  });

  it('refuses a receipt for another buyer', async () => {
    const v = base();
    const check = await verifyReceipt(v.receipt, {
      messages: messagesFor(v.prompt),
      completion: v.completion,
      buyer: 'somebody-else',
    });
    expect(check.boundToExchange).toBe(false);
    expect(check.problem).toContain('not somebody-else');
  });

  it('reads amounts as BigInt, so a value above 2^53 is exact', async () => {
    const big = cases.find((c) => c.name === 'values a double cannot hold');
    expect(big).toBeDefined();
    // Reading these as JavaScript numbers rounds them, and the digest changes.
    // That this vector verifies at all is the assertion.
    const check = await verifyReceipt(big!.receipt);
    expect(check.signatureValid).toBe(true);
    expect(BigInt(big!.receipt.units)).toBe(9007199254740993n);
  });
});
