import { CodeSample } from '@/components/CodeSample';
import DocSidebar from '@/components/DocSidebar';
import Navigation from '@/components/Navigation';

export const metadata = {
  title: 'Configuration',
  description:
    'Every field in a matrixd config file: what it does, what it defaults to, and which ones change how the node is reachable.',
};

/**
 * This page used to document a JSON config with node.name, storage.maxSize,
 * logging.level, network.p2p.maxPeers and security.encryption.keyRotation. The
 * real config is YAML and shares not one field with that. Everything below is
 * read from services/core/internal/node/node.go, and `matrixd -init` writes
 * exactly this shape.
 */
const FULL = `network:
  listen_addr: /ip4/127.0.0.1/tcp/9000   # libp2p multiaddr; 0.0.0.0 to accept peers
  bootstrap_peers: []                    # multiaddrs to dial on start

storage:
  engine: pebble
  path: ./data

security:
  enable_acls: true                      # when true, every RPC needs a key
  allow_unsigned_agents: false
  api_keys:
    - key: <64 hex chars>                # generated by \`matrixd -init\`
      role: admin                        # admin | operator | viewer
      name: local-admin
      account: ""                        # on-chain account this key spends from

admin:
  addr: 0.0.0.0:9090                     # gRPC: deploy, health, logs

market:
  addr: 0.0.0.0:9091                     # gRPC: matrix.market.v1.MarketService

inference:
  addr: 0.0.0.0:9092                     # gRPC: matrix.inference.v1.InferenceService
  echo_provider: demo-inference-provider # GPU-free backend; "" registers none
  backends:                              # what this node actually serves
    - id: my-gpu-box
      kind: local-http                   # echo | openai | local-http
      base_url: http://127.0.0.1:8000
      models: [llama-3.3-70b]            # what a model request routes on
      capacity: 1000
      price_per_unit: 3

connect:
  addr: 0.0.0.0:9093                     # HTTP/JSON + /v1/chat/completions; "off" disables
  public_reads: false                    # open Get*/List* to keyless callers
  signed_writes: false                   # open the signature-authorised writes
  rate_limit_per_minute: 600             # per caller; 0 disables
  rate_limit_burst: 120
  allowed_origins:                       # browser origins; empty = no browser may call
    - http://127.0.0.1:5173
    - http://localhost:5173

consensus:
  validators: []                         # GENESIS set: hex account ids; empty = this node alone
  epoch_length: 100                      # blocks between set changes taking effect; must match everywhere
  approved_changes: []                   # set changes this operator votes for and offers
  eject_equivocators: true               # remove a validator proven to have double-voted
  stake:
    enabled: false                       # voting power = bonded MATRIX; off = one vote each
    min_bond: null                       # null = 1e15 base units; 0 = no minimum
    unbonding_period: 0                  # 0 = 1000 blocks after leaving before withdrawal
    bond: 0                              # what THIS node keeps bonded from its own account
  fee_basis_points: 0                    # cut of each transfer to validators; capped at 100 in code
  rewards:
    per_block: 0                         # pool payout per block, shared by the providers it paid
    half_life: 0                         # 0 = halve every 1,000,000 blocks
    approved_providers: []               # "add:<account id>"; needs a quorum of operators

genesis:
  allocations: []                        # [{account, amount}] credited once, at first start
  reward_pool: 1000000000000000000       # native base units held for funding accounts

bridge:
  contract: ""                           # WrappedMatrix address; empty leaves the bridge off
  chain_id: 0
  watch:
    enabled: false
    rpc_url: ""
    start_block: 0
    confirmations: null                  # null = 12
    poll_interval: 0s                    # 0 = default
    max_block_span: 0`;

const MINIMAL = `network:
  listen_addr: /ip4/127.0.0.1/tcp/9000
storage:
  engine: pebble
  path: ./data`;

const VALIDATORS = `consensus:
  validators:
    - 3f9a...   # every node in the set lists the SAME ids
    - 7c21...
    - b0e4...
  epoch_length: 100
  approved_changes:
    - add:9f2c1e4b...    # a new validator's consensus identity (its public key, hex)
    - remove:7c21...     # an account id to eject`;

type Field = { name: string; def: string; note: string };

const sections: { title: string; blurb: string; fields: Field[] }[] = [
  {
    title: 'network',
    blurb: 'How the node reaches peers.',
    fields: [
      {
        name: 'listen_addr',
        def: '/ip4/127.0.0.1/tcp/9000',
        note: 'A libp2p multiaddr. Loopback keeps a dev node private; use /ip4/0.0.0.0/tcp/9000 to accept peers.',
      },
      {
        name: 'bootstrap_peers',
        def: '[]',
        note: 'Multiaddrs dialled at start. A failure is logged, not fatal.',
      },
    ],
  },
  {
    title: 'storage',
    blurb: 'One embedded Pebble store holds the ledger, the token chain and the committed blocks.',
    fields: [
      { name: 'engine', def: 'pebble', note: 'The only engine.' },
      { name: 'path', def: './data', note: 'Directory for the store. Back this up; it is the node state.' },
    ],
  },
  {
    title: 'security',
    blurb: 'Authentication for every surface.',
    fields: [
      {
        name: 'enable_acls',
        def: 'true',
        note: 'With it on, admin, market, inference and the HTTP endpoint all require a key. With it off they are open to anyone who can reach the port.',
      },
      {
        name: 'api_keys',
        def: 'one generated key',
        note: 'A list of {key, role, name, account}. `matrixd -init` writes one admin key, which is why the file is mode 0600. An unset role means admin; an unrecognised one falls to viewer. `account` is the on-chain account the key spends from, which is what makes it usable on /v1/chat/completions: that protocol carries no buyer field, so the key has to say whose balance to charge. The balance stays on the ledger; the node must hold that account\'s signing key to settle for it.',
      },
      {
        name: 'allow_unsigned_agents',
        def: 'false',
        note: 'Whether unsigned agent code may be loaded.',
      },
    ],
  },
  {
    title: 'admin / market / inference',
    blurb: 'The gRPC listeners, one port each.',
    fields: [
      { name: 'admin.addr', def: '0.0.0.0:9090', note: 'Deploy, health and log services.' },
      { name: 'market.addr', def: '0.0.0.0:9091', note: 'The marketplace: providers, jobs, balances, transfers.' },
      { name: 'inference.addr', def: '0.0.0.0:9092', note: 'LLM inference jobs.' },
      {
        name: 'inference.echo_provider',
        def: 'demo-inference-provider',
        note: 'Registers a deterministic GPU-free backend under this provider id at start, so the inference path works with no models. Empty registers none.',
      },
      {
        name: 'inference.backends',
        def: 'none',
        note: 'The backends this node serves. Each entry needs an id, a kind (echo, openai for any OpenAI-compatible vendor, or local-http for a model server on this machine), a capacity and a price_per_unit; base_url and api_key_env configure the upstream, and models lists what it serves. Each entry is registered twice at start: in the inference registry as the thing that fulfills the job, and on the order book as a provider that can reserve capacity and be paid.',
      },
      {
        name: 'inference.backends[].models',
        def: 'none',
        note: 'The model identifiers this backend serves, lowercased and de-duplicated. A request naming a model is routed to the cheapest provider advertising it that still has capacity. A backend that declares no model is still reachable by naming its provider id.',
      },
    ],
  },
  {
    title: 'connect',
    blurb: 'The HTTP surface a browser can use. Raw gRPC needs HTTP/2 trailers no browser can produce.',
    fields: [
      {
        name: 'addr',
        def: '0.0.0.0:9093',
        note: 'Serves the market and inference services as JSON. Set to "off" to disable it entirely.',
      },
      {
        name: 'public_reads',
        def: 'false',
        note: 'Opens the read methods (Get*, List*) to callers with no API key. Writes still require one, so this cannot move money or reserve capacity. Off by default and it stays that way: chain data is public information, but turning this on by default would widen what an unauthenticated caller can see on every node that already exists. Turn it on for a PUBLIC endpoint, because a browser cannot hold a secret and the alternatives - shipping a key to everyone who loads the page, or not reading the chain from a page at all - are both worse.',
      },
      {
        name: 'signed_writes',
        def: 'false',
        note: "Opens the three write methods whose authority is a client signature rather than an API key: SubmitSignedTransfer, SettleInferenceJob and RunInferenceJob. It is what a self-custody page needs, because a browser cannot keep a key secret. Turning it on ALSO makes RunInferenceJob require the buyer's signed run authorization, and that is not a separate switch on purpose: without it `buyer` is just a string, so an open RunInferenceJob would let anyone name someone else's funded account, have a provider do the work, and never sign for it. Nothing else is opened - FundAccount, RegisterProvider, SubmitJob, CompleteJob and CancelJob carry no signature that could stand in for a credential.",
      },
      {
        name: 'rate_limit_per_minute',
        def: '600',
        note: 'How many requests one caller may make per minute, counted per credential where one is presented and per remote address otherwise. Nothing bounded this before, on an endpoint where every call reserves capacity, reads a ledger or runs a model. A refusal is a 429 with Retry-After, in the envelope the caller\'s protocol expects. Zero disables it. Note the limitation: the remote address is the TCP peer, not X-Forwarded-For, so behind a reverse proxy every unauthenticated request looks like one caller and the proxy should limit too.',
      },
      {
        name: 'rate_limit_burst',
        def: '120',
        note: 'How many requests a caller may make back to back before the sustained rate applies. Zero means one minute\'s worth. CORS preflights are not counted, since a browser sends one per request.',
      },
      {
        name: 'allowed_origins',
        def: 'the Console dev origins',
        note: 'Empty means no browser may call the endpoint, and that is the default for a config that omits it. A wide-open policy on a localhost daemon lets any page the operator visits drive their node. Non-browser callers send no Origin and are unaffected. "*" is for development.',
      },
    ],
  },
  {
    title: 'consensus',
    blurb:
      'The validator set. Every node in a network must start from the same ids and agree on epoch_length, and on whether stake is enabled, or they derive different leader schedules and different quorums. The set itself is chain state: once it has changed, each node resumes the set the chain arrived at and this file no longer decides it.',
    fields: [
      {
        name: 'validators',
        def: '[]',
        note: 'The GENESIS set, as hex account ids. It seeds a fresh store and is ignored once the chain has changed the set. This node’s own consensus identity is always added, so an empty list is a working single-validator node.',
      },
      {
        name: 'epoch_length',
        def: '100',
        note: 'How many committed blocks make an epoch. A set change carried by a committed block takes effect at the next height that is a multiple of this, so every node switches at the SAME height - nodes that disagree about it would switch at different heights, which is a fork. Zero means 100.',
      },
      {
        name: 'approved_changes',
        def: '[]',
        note: 'Set changes this operator votes for, written as add:<64-hex public key> or remove:<64-hex account id> - the same text the node prints in its log. A node offers the changes listed here and re-offers them until they commit, and prevotes nil on a block carrying anything else, so a change needs a quorum of operators to have listed it. Empty means this node approves no membership change, which is the safe default. A typo fails startup rather than silently approving nothing.',
      },
      {
        name: 'stake.enabled',
        def: 'false',
        note: 'Turns bonded stake on. Voting power becomes an account’s bonded native MATRIX rather than one vote per validator, admission requires stake.min_bond, and a validator proven to have equivocated loses its whole bond to the reward pool instead of only its place. Off, the network runs as a permissioned set of equals - coherent for operators who know each other, and not safe for a set anyone may join, because a quorum counted in heads can be bought for the price of a few identities.',
      },
      {
        name: 'stake.min_bond',
        def: 'null (1e15 base units)',
        note: 'What an account must have bonded before the network may admit it as a validator. Null takes the default, a thousandth of the supply cap; an explicit 0 means no minimum, which is only appropriate on a network not using stake for security. A bond is necessary to be admitted and never sufficient: a quorum of operators still has to approve the change.',
      },
      {
        name: 'stake.unbonding_period',
        def: '0 (1000 blocks)',
        note: 'How many blocks after LEAVING the validator set an account waits before it may withdraw its bond. A sitting validator may not withdraw at all. The delay is why a bond deters anything: without it a validator could equivocate, be ejected, and withdraw before the network committed the slash, so it has to be long enough for evidence to be gossiped, voted on and committed. A withdrawal submitted early waits in the mempool and lands by itself.',
      },
      {
        name: 'stake.bond',
        def: '0',
        note: 'How much of its own native MATRIX this node keeps bonded. The node bonds the shortfall itself and keeps topping it up, because bonding must be signed by the validator’s own key and that key lives inside the node. Its consensus account has to hold the coins first - the id is printed at startup - and the node says so plainly if it does not. Zero bonds nothing, so on a staked network the node cannot be admitted.',
      },
      {
        name: 'fee_basis_points',
        def: '100',
        note: 'The protocol fee taken from every value transfer a committed block carries, in hundredths of a percent, paid to the validator set pro rata by voting power. It is what makes a bond worth posting: without it stake is a pure cost. Taken OUT of the amount, so a 10,000 transfer at 1% credits the recipient 9,900 - adding it to the sender would make a transfer that was affordable at proposal time unaffordable at apply time. Capped at 100 IN CODE, so a mistyped 1000 fails at startup instead of taking ten times the cut. A generated config sets it to 100 (1%), the code cap; set it to 0 for a fee-free network. Every node must agree on the rate. It reaches ALL consensus-settled value: marketplace settlement AND a plain `matrix wallet transfer` are signed transfers that settle through consensus, so both pay it - there is no path that escapes the fee.',
      },
      {
        name: 'rewards.per_block',
        def: '0',
        note: 'What the genesis reward pool pays out per committed block, shared among the REGISTERED providers that block paid, pro rata by how much. A fixed budget rather than a percentage of what a provider earned, because consensus cannot see work: a percentage of a transfer is a money pump, since anyone can send coins to an account they also control and collect it. A fixed budget means faked volume moves a share and cannot increase the total, so the pool empties on schedule. Zero leaves the pool untouched.',
      },
      {
        name: 'rewards.half_life',
        def: '0 (1,000,000 blocks)',
        note: 'How many blocks halve the emission. The schedule is a right shift, so it reaches exactly zero rather than trailing off. Total ever paid is about 1.44 × per_block × half_life, so a target spend T over a half-life H wants per_block near T / (1.44 × H).',
      },
      {
        name: 'rewards.approved_providers',
        def: '[]',
        note: 'This operator’s allow-list of registry changes, as add:<64-hex account id> or remove:<id>. A registration needs a QUORUM of operators to have listed it, the same as admitting a validator, and the node offers what it has listed until the change commits. Without a registry the emission would pay whoever happened to receive a transfer. Registration takes effect from the next block, so a block cannot register an account and pay it in the same breath.',
      },
      {
        name: 'eject_equivocators',
        def: 'true',
        note: 'Vote to remove a validator this node holds proof equivocated - two votes for different blocks at one height, round and phase, both signed by that validator’s key - with no entry in approved_changes. The evidence proves itself and every node checks it rather than trusting a peer, so there is no operator judgement to make. False keeps detection, recording and gossip and leaves the removal to you.',
      },
    ],
  },
  {
    title: 'genesis',
    blurb: 'Applied once, on first start, and idempotent afterwards. Nothing is minted past the 1,000,000,000 MATRIX cap.',
    fields: [
      { name: 'allocations', def: '[]', note: 'A list of {account, amount} in native base units.' },
      {
        name: 'reward_pool',
        def: '1e18 (the whole cap)',
        note: 'Held in the reserved account native/reward-pool. `matrix fund` moves coins out of it; it never mints. On a validator SET, `fund` refuses: reward-pool funding is not consensus-ordered, so it would move value on one node and nowhere else, diverging each node\'s pool and forking the provider emission. Set the allocation in every node\'s genesis instead, or move value with a signed transfer.',
      },
    ],
  },
  {
    title: 'bridge',
    blurb: 'The lock-and-mint bridge to wMATRIX on Ethereum. Off unless a contract address is set.',
    fields: [
      { name: 'contract', def: '""', note: 'Deployed WrappedMatrix address. Empty leaves the whole subsystem off.' },
      { name: 'chain_id', def: '0', note: 'EVM chain id the contract is deployed on.' },
      {
        name: 'watch.enabled',
        def: 'false',
        note: 'Runs the burn-to-unlock watcher inside the node: it polls for Burned events past a confirmation depth, exactly once per event. What it does with one depends on the size of the validator set. A single node releases the escrow itself. On a SET the release is consensus-ordered: the watcher submits an attestation and the engine releases escrow on the block where attesting voting power crosses quorum, so turn this on for EVERY validator - a burn stays pending until more than two thirds of the power has attested it, and one watching node produces one attestation.',
      },
      { name: 'watch.rpc_url', def: '""', note: 'Ethereum JSON-RPC endpoint for the watcher.' },
      {
        name: 'watch.confirmations',
        def: 'null (12)',
        note: 'Blocks to wait behind head. Set 0 only on a chain with instant finality, such as a local hardhat node.',
      },
      {
        name: 'watch.start_block',
        def: '0',
        note: 'Where to begin scanning. A persisted cursor takes over after the first run, so a restart does not rescan.',
      },
    ],
  },
];

export default function ConfigurationPage() {
  return (
    <>
      <Navigation />
      <div className='min-h-screen bg-black'>
        <div className='pt-16'>
          <div className='flex flex-col lg:flex-row'>
            <DocSidebar />

            <main className='min-w-0 flex-1 p-4 sm:p-6 lg:ml-64 lg:p-8'>
              <div className='mx-auto max-w-4xl'>
                <article className='text-gray-100'>
                  <div className='mb-10 rounded-xl border border-primary-400/20 bg-gradient-to-r from-primary-400/10 via-accent-300/10 to-primary-400/10 p-8'>
                    <h1 className='mb-4 text-4xl font-bold text-white'>Configuration</h1>
                    <p className='text-xl text-gray-100'>
                      One YAML file, written by <code className='text-white'>matrixd -init</code> and read at start.
                      Every field below is real.
                    </p>
                  </div>

                  <h2 className='mb-4 mt-8 text-3xl font-bold text-white'>The whole file</h2>
                  <CodeSample label='config.yaml' code={FULL} />
                  <p className='mt-4 text-gray-300'>
                    A missing section takes its defaults, so this is also a valid config:
                  </p>
                  <CodeSample className='mt-4' label='config.yaml (minimal)' code={MINIMAL} />

                  {sections.map((section) => (
                    <section key={section.title}>
                      <h2 className='mb-2 mt-12 text-3xl font-bold text-white'>{section.title}</h2>
                      <p className='mb-4 text-gray-300'>{section.blurb}</p>
                      <dl className='space-y-4'>
                        {section.fields.map((field) => (
                          <div key={field.name} className='rounded-xl border border-gray-800 bg-gray-900/50 p-5'>
                            <dt className='flex flex-wrap items-baseline gap-x-3 gap-y-1'>
                              <code className='text-base font-semibold text-white'>{field.name}</code>
                              <span className='text-caption-regular text-grayscale-400'>default {field.def}</span>
                            </dt>
                            <dd className='mt-2 text-sm leading-relaxed text-gray-300'>{field.note}</dd>
                          </div>
                        ))}
                      </dl>
                    </section>
                  ))}

                  <h2 className='mb-4 mt-12 text-3xl font-bold text-white'>Joining an existing network</h2>
                  <p className='mb-4 text-gray-300'>
                    Two things have to match: the bootstrap peers you dial, and the validator set. Every node derives
                    its leader schedule from that list, so a node with a different list is on a different network even
                    if it can reach the others.
                  </p>
                  <CodeSample label='config.yaml' code={VALIDATORS} />

                  <h2 className='mb-4 mt-12 text-3xl font-bold text-white'>Environment</h2>
                  <p className='mb-4 text-gray-300'>
                    <code className='text-white'>MATRIX_ADMIN_API_KEY</code> adds one admin key on top of whatever the
                    config lists, for deployments that keep secrets out of files. It is additive, not a replacement.
                  </p>

                  <div className='mt-10 rounded-xl border border-primary-400/20 bg-primary-400/10 p-6'>
                    <h2 className='mb-4 text-2xl font-bold text-white'>Next</h2>
                    <ul className='mb-0 list-disc space-y-3 pl-6 text-gray-100'>
                      <li>
                        <a href='/docs/guides/network-setup' className='text-accent-200 underline hover:text-accent-100'>
                          Network setup
                        </a>{' '}
                        - running more than one node
                      </li>
                      <li>
                        <a href='/docs/architecture' className='text-accent-200 underline hover:text-accent-100'>
                          Architecture
                        </a>{' '}
                        - what each listener belongs to
                      </li>
                    </ul>
                  </div>
                </article>
              </div>
            </main>
          </div>
        </div>
      </div>
    </>
  );
}
